version: '3'

services:
    shlink_web_component:
        container_name: shlink_web_component
        image: node:20.5-alpine
        command: /bin/sh -c "cd /shlink-web-component && npm i && npm run dev"
        volumes:
            - ./:/shlink-web-component
        ports:
            - '3002:3002'
            - '3003:3003'
